### ISSUE TITLE
null valued array when putting filtered simulated oscillator into spectral.compute_spectrum

### ISSUE THREAD

**Issue by limwik** [neurodsp-tools/neurodsp#134] opened 2019-02-13 00:25 UTC
I am getting an array with null values as output when I put sim.sim_oscillator into filt.filter_signal and that into spectral.compute_spectrum. code example (with a bunch of printed arrays to show where the problem is):

import numpy as np
np.random.seed(0)

from neurodsp import spectral, sim, filt

%matplotlib inline
import matplotlib.pyplot as plt
import scipy as sp
from scipy import signal

n_samples_cycle = 100
fs = 1000
osc_freq = 6.5
fc = 20
oscA = sim.sim_oscillator(n_samples_cycle, fs, osc_freq, rdsym=.5)
oscB = sim.sim_oscillator(n_samples_cycle, fs, osc_freq, rdsym=.05)
oscC = filt.filter_signal(oscA, fs, 'lowpass', (None,fc))
oscD = filt.filter_signal(oscB, fs, 'lowpass', (None,fc))

print("psdA:")
print(oscA[:])
print("psdB:")
print(oscB[:])

# Plot time series
plt.figure(figsize=(24,3))
plt.plot(oscA, 'k', label='rdsym='+str(.5), alpha=.8)
plt.plot(oscB, 'r', label='rdsym='+str(.3), alpha=.8)
plt.plot(oscC, 'b', label='rdsym='+str(.5), alpha=.8)
plt.plot(oscD, 'g', label='rdsym='+str(.3), alpha=.8)
plt.ylim((-1.1, 1.7))
plt.xlim((0, 1000))
plt.legend()
plt.xlabel('Time (sample)')
plt.ylabel('Voltage')

# Plot power spectrum
fA, psdA = spectral.compute_spectrum(oscA, 1000)
fB, psdB = spectral.compute_spectrum(oscB, 1000)
fC, psdC = spectral.compute_spectrum(oscC, 1000)
fD, psdD = spectral.compute_spectrum(oscD, 1000)
print("fA")
print(fA[:])
print("fB")
print(fB[:])
print("fC")
print(fC[:])
print("fD")
print(fD[:])
print("psdA")
print(psdA[:])
print("psdB")
print(psdB[:])
print("psdC")
print(psdC[:])
print("psdD")
print(psdD[:])
plt.figure(figsize=(20,5))
plt.loglog(fA, psdA, 'k', alpha=.5)
plt.loglog(fB, psdB, 'r', alpha=.5)
plt.loglog(fC, psdC, 'b', alpha=.5)
plt.loglog(fD, psdD, 'g', alpha=.5)
plt.xlabel('Frequency (Hz)')
plt.ylabel('Power')

**Comment by rdgao** [comment] 2019-02-13 00:41
I was able to reproduce the problem with your code (thanks!). 

The issue is that filt.filter_signal() pads the edges of the returned time series with `nan`s, which, when then passed into compute_spectrum, results in `nan`s all the way. 

This is done by default because the first and last bit of the signal is only partially filtered via convolution, so it's not technically valid. Although in practice, esp if you epoch the data later, it doesn't _really_ matter.

To bypass this, either manually clip the edges of the time series returned from filter_signal, or set remove_edge_artifacts=False (see doc for filt.filter_signal).

**Comment by srcole** [comment] 2019-02-15 06:10
So, to address the confusion that caused this issue, should we raise a warning in `compute_spectrum` when a signal is input with some NaNs?

I think it'd be good to determine the NaN edges, remove them and return the computed spectrum on the non-NaN signal, and raise a warning to the user saying that they passed in a signal with NaNs on the edges.

**Comment by limwik** [comment] 2019-02-15 19:38
That would be the functionality I would expect as an end-user. It would
allow me to use it without taking extra steps if I wish to, but makes me
aware of what it is doing behind the scenes beyond the standard
functionality in case that is not my intention. Incidentally, I am new to
python and its libraries - what would be the most efficient way of trimming
the nans from the edges of the data? I did some (cursory) searching but did
not find a class with a function that does that.

**Comment by rdgao** [comment] 2019-02-26 19:31
@limwik you can use `numpy.isnan` to find the indices where your array is `nan`, and pass the rest of the array with the complement (non-nan) indices.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.isnan.html

**Comment by TomDonoghue** [comment] 2019-02-26 19:47
We have a procedure in filter to drop NaN edges, if they are there. Why don't we just add this same procedure to be used in spectral?

**Comment by rdgao** [comment] 2019-02-26 20:34
yeah, that's pretty much all that needs to be added

**Comment by rdgao** [comment] 2019-03-16 02:23
actually, now that I'm reading this again, if this was implemented in spectral, should it be applied across the board in all the other functions too? It wouldn't make sense if spectral handled this without complaint, but none of the other modules did.

Also: on the one hand, I can see this making sense within our ecosystem, since signals that come out of filter should be useable by other modules. On the other hand, is this the appropriate convention for handling nans in unknown signals, i.e., signals not produced by neurodsp functions? Let's say you pass something to scipy, should we expect it to play nicely with nans automatically? 

Maybe what would make more sense is for filter to return a clipped signal as an output option, i.e. valid in np.convolve, though that would obviously misalign any time indexing. Or have a utility one-liner function that automatically clips signals with nan edges. But I don't think compute_spectrum should just automatically do this.

**Comment by TomDonoghue** [comment] 2019-03-16 05:28
Currently the tooling to drop and replace NaNs at the edges is in `filter`, as `_remove_nans` and `_restore_nans`. I was broadly thinking these would be moved into a general utility file. 

This general procedure (drop edge nans -> run operation -> replace edge nans) is actually well placed for a decorator, in which case we could easily have it set up that basically all NDSP functions all just play nice with edge nans, or at least easily tag all the functions we want to do this. 

But whether we want to default to doing this - is less clear. It seems like we would want to preserve shape, and not trim things. If we're going to need some NaN handling anyways, maybe we do just roll with it pretty generally (and document it, print notes, etc).

**Comment by rdgao** [comment] 2019-03-16 19:06
I definitely don't think it should be applied by default, to keep signal length. I'd vote for having that as utility and letting the user call it when needed, because I don't think this is a very common use case either.

**Comment by TomDonoghue** [comment] 2019-08-19 05:18
@rdgao: any strong thoughts or updates on how you think we should handle and propagate NaNs across the module? I'm finally doing the last sweep to solidify 2.0. If you have no strong / new thoughts, I'll just go with what seems to be the most sensible and straight-forward approach, taking from this thread, when I come back to this tomorrow or so.

**Comment by rdgao** [comment] 2019-08-19 22:28
just read through again, no strong preference. I think a warning after the filter or when compute_spectrum detects nans is sufficient, given we have those utility functions

**Comment by TomDonoghue** [comment] 2019-09-09 16:02
Alright, the original question in this issue is quite old, and the code comments are all outdated. 

In the end, with the move to 2.0, we have not fundamentally changed any of our NaN behaviour. Maybe this will change in the future, and I've moved to a new issue for any ideas on that (#171 ), but I'm going to close this one now. 

@limwik : if you're still following this, then feel free to let us know any suggestions / ideas over in #171

**Closed by TomDonoghue** 2019-09-09 16:02 UTC
Labels: 1.1
